# toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}

# python {{{
[[plugins]]
    repo = 'Vimjas/vim-python-pep8-indent'
    on_ft = ['python']
# }}}

# markdown {{{
[[plugins]]
    repo = 'plasticboy/vim-markdown'
    on_ft = ['markdown']
    hook_source = '''
        let g:vim_markdown_new_list_item_indent = 2
    '''
# }}}

# dosbatch {{{
[[plugins]]
    repo = 'k-takata/vim-dosbatch-indent'
    on_ft = ['dosbatch']
# }}}

# html or css {{{
[[plugins]]
    repo = 'mattn/emmet-vim'
    on_ft = ['html', 'css', 'htmldjango', 'javascriptreact']
# }}}

# javascript {{{
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']
# }}}

# jsx {{{
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascriptreact']

[[plugins]]
repo = 'alampros/vim-styled-jsx'
on_ft = ['javascriptreact']
# }}}

# fish shell {{{
[[plugins]]
    repo = 'dag/vim-fish'
    on_ft = ['fish']
# }}}
