[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_add = '''
    if dein#util#_is_windows()
        let g:vimproc#download_windows_dll = 1
    endif
'''
hook_post_update = '''
    if executable('make')
        let cmd = 'make'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = ''
    endif
    let g:dein#plugin.build = cmd
'''

# visual {{{
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
    autocmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
                \ 'colorscheme' : 'wombat',
                \ 'component' : {
                \   'mode' : "%{ expand('%:t') =~ 'NERD_tree' ? 'NERDTree' : lightline#mode() }",
                \   'fileencoding' : "%{ winwidth(0) < 50 ? '' : (&fenc !=# '' ? &fenc : &enc) }",
                \   'fileformat' : "%{ winwidth(0) < 50 ? '' : &ff }",
                \   'filetype' : "%{ winwidth(0) < 50 ? '' : (&ft !=# '' ? &ft : 'no ft') }"
                \   },
                \ 'component_visible_condition' : {
                \   'fileencoding' : 'winwidth(0) > 50',
                \   'fileformat' : 'winwidth(0) > 50',
                \   'filetype' : 'winwidth(0) > 50'
                \   },
                \ 'component_function' : {
                \   'filename' : 'LightLineFileName',
                \   'modified' : 'LightLineModified'
                \   },
                \ }
    
    function! LightLineFileName()
        let fname = expand('%:t')
        return fname =~ 'NERD_tree' ? '' : fname
    endfunction
    function! LightLineModified()
        return &modifiable ? (&modified ? '+' : '') : (&ft =~ 'help\|nerdtree' ? '' : '-')
    endfunction
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_setConceal = 0
'''
# }}}

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
    let g:NERDSpaceDelims = 1
    let g:NERDDefaultAlign = 'left'
    let g:NERDAltDelims_c = 1
    let g:NERDAltDelims_python = 1
    filetype plugin on
    nmap <Leader>x <Plug>NERDCommenterToggle
    vmap <Leader>x <Plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = '''
    let g:AutoPairsFlyMode = 1
    let g:AutoPairsShortcutBackInsert = '<C-B>'
'''

[[plugins]]
repo = 'tpope/vim-surround'
