# toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}

# python {{{
[[plugins]]
    repo = 'davidhalter/jedi-vim'
    on_ft = ['python']
    hook_source = '''
        autocmd FileType python setlocal completeopt-=preview

        let g:jedi#completions_enabled = 0
    '''

[[plugins]]
    repo = 'zchee/deoplete-jedi'
    on_ft = ['python']

[[plugins]]
    repo = 'Vimjas/vim-python-pep8-indent'
    on_ft = ['python']
# }}}

# markdown {{{
[[plugins]]
    repo = 'plasticboy/vim-markdown'
    on_ft = ['markdown']
    hook_source = '''
        let g:vim_markdown_new_list_item_indent = 2
    '''

[[plugins]]
    repo = 'iamcco/markdown-preview.nvim'
    on_ft = ['markdown', 'pandoc.markdown', 'rmd']
    build = 'cd app & npm install'
    hook_source = '''
        let g:mkdp_auto_start = 1
    '''
# }}}

# dosbatch {{{
[[plugins]]
    repo = 'k-takata/vim-dosbatch-indent'
    on_ft = ['dosbatch']
# }}}

# html or css {{{
[[plugins]]
    repo = 'mattn/emmet-vim'
    on_ft = ['html', 'css', 'htmldjango']
# }}}

# fish shell {{{
[[plugins]]
    repo = 'dag/vim-fish'
    on_ft = ['fish']
# }}}
