# toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}

# python {{{
[[plugins]]
    repo = 'zchee/deoplete-jedi'
    on_ft = ['python']
# }}}

# markdown {{{
[[plugins]]
    repo = 'plasticboy/vim-markdown'
    on_ft = ['markdown']
    hook_source = '''
        let g:vim_markdown_new_list_item_indent = 2
    '''
# }}}
