[[plugins]]
repo = 'scrooloose/nerdcommenter'
rev = 'v2.6.0'
on_map = ['<Plug>NERDCommenterToggle']
hook_add = '''
    nmap <Leader>x <Plug>NERDCommenterToggle
    vmap <Leader>x <Plug>NERDCommenterToggle
'''
hook_source = '''
    let g:NERDSpaceDelims = 1
    let g:NERDDefaultAlign = 'left'
    let g:NERDAltDelims_c = 1
    let g:NERDAltDelims_python = 1
    " filetype plugin on
'''
