[[plugins]]
repo = 'easymotion/vim-easymotion'
rev = 'v3.0.1'
on_map = [
    # '<Plug>(easymotion-f)', '<Plug>(easymotion-F)',
    '<Plug>(easymotion-bd-f)', '<Plug>(easymotion-overwin-f)', '<Plug>(easymotion-overwin-f2)',
    '<Plug>(easymotion-bd-jk)', '<Plug>(easymotion-overwin-line)',
    '<Plug>(easymotion-sn)', '<Plug>(easymotion-next)', '<Plug>(easymotion-prev)',
    '<Plug>(easymotion-lineforward)', '<Plug>(easymotion-j)',
    '<Plug>(easymotion-k)', '<Plug>(easymotion-linebackward)'
]
hook_add = '''
    " <Leader>f{char} to move to {char}
    map  <Leader>f <Plug>(easymotion-bd-f)
    nmap <Leader>f <Plug>(easymotion-overwin-f)
    " map f <Plug>(easymotion-f)
    " map F <Plug>(easymotion-F)

    " s{char}{char} to move to {char}{char}
    nmap <Leader>s <Plug>(easymotion-overwin-f2)

    " Move to line
    map  <Leader>L <Plug>(easymotion-bd-jk)
    nmap <Leader>L <Plug>(easymotion-overwin-line)

    " Move to word
    map  <Leader>w <Plug>(easymotion-bd-w)
    nmap <Leader>w <Plug>(easymotion-overwin-w)

    map / <Plug>(easymotion-sn)
    map n <Plug>(easymotion-next)
    map N <Plug>(easymotion-prev)

    map <Leader>h <Plug>(easymotion-linebackward)
    map <Leader>j <Plug>(easymotion-j)
    map <Leader>k <Plug>(easymotion-k)
    map <Leader>l <Plug>(easymotion-lineforward)
'''
hook_source = '''
    set nohlsearch
    let g:EasyMotion_startofline = 0 " keep cursor column when JK motion
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1
    let g:EasyMotion_use_migemo = 1
'''
