[[plugins]]
repo = 'jiangmiao/auto-pairs'
rev = '39f06b8'
hook_add = '''
    let g:AutoPairsFlyMode = 1
    let g:AutoPairsShortcutBackInsert = '<C-B>'
    let g:AutoPairsMoveCharacter = "(){}\"'"
'''
