[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
rev = 'eadf42a'
depends = [
    'nvim-lspconfig',
]
hook_add = '''
lua << EOF
local lsp_installer = require("nvim-lsp-installer")

local default_install_servers = {
    "pyright",
    "tsserver"
}
for _, name in pairs(default_install_servers) do
    local is_found, server = lsp_installer.get_server(name)
    if is_found and not server:is_installed() then
        print("Installing " .. name)
        server:install()
    end
end

-- installしているserverの起動準備をします。
-- `server` に格納しているのはServer classで、
-- server nameやsetup functionを含んでいます。
lsp_installer.on_server_ready(function(server)
  local opts = {}

  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  -- serverに対応しているfiletypeのbufferを開いたら、
  -- 実行するfunctionを設定します。
  opts.on_attach = function(client, buffer_number)
    local keymap_opts = { noremap=true, silent=true }

    buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', keymap_opts)
    buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', keymap_opts)
    buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', keymap_opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', keymap_opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', keymap_opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', keymap_opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.diagnostic.open_float()<CR>', keymap_opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.diagnostic.goto_prev()<CR>', keymap_opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.diagnostic.goto_next()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.diagnostic.setloclist()<CR>', keymap_opts)
    buf_set_keymap('n', '<space>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', keymap_opts)
  end

  -- LSPのsetupをします。
  -- setupをしないとserverは動作しません。
  server:setup(opts)
end)
EOF
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
rev = 'v0.1.2'
