#[[plugins]]
#repo = 'scrooloose/syntastic'
#on_ft = ['python']

# [[plugins]]
# repo = 'scrooloose/nerdtree'
# on_cmd = ['NERDTreeToggle']
# depends = ['nerdtree-git-plugin']
# hook_add = '''
#     nnoremap <silent> <C-T>      :NERDTreeToggle<CR>
#     vnoremap <silent> <C-T> <ESC>:NERDTreeToggle<CR>
#     onoremap <silent> <C-T>      :NERDTreeToggle<CR>
#     inoremap <silent> <C-T> <ESC>:NERDTreeToggle<CR>
#     cnoremap <silent> <C-T> <C-U>:NERDTreeToggle<CR>
#     let g:NERDTreeShowHidden = 1
#     let g:NERDTreeShowBookmarks = 1
#     autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
# '''

# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'
# lazy = 1
# hook_source = '''
#     let g:NERDTreeGitStatusIndicatorMapCustom = {
#         \ "Modified"  : "+",
#         \ "Staged"    : "*",
#         \ "Untracked" : "✭",
#         \ "Renamed"   : "➜",
#         \ "Unmerged"  : "═",
#         \ "Deleted"   : "x",
#         \ "Dirty"     : "✗",
#         \ "Clean"     : "✔︎",
#         \ "Unknown"   : "?"
#         \ }
# '''

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']
hook_add = '''
    nnoremap <silent> <LEADER>m :OverCommandLine<ENTER>%s/
'''

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = ['<Plug>(quickhl-manual-this)', '<Plug>(quickhl-manual-reset)']
hook_add = '''
    nmap <Space>m <Plug>(quickhl-manual-this)
    xmap <Space>m <Plug>(quickhl-manual-this)
    nmap <Space>M <Plug>(quickhl-manual-reset)
    xmap <Space>M <Plug>(quickhl-manual-reset)
'''

# [[plugins]]
# repo = 'skanehira/vsession'
# on_cmd = ['SaveSession', 'LoadSession', 'DeleteSession']
# hook_add = '''
#     let g:vsession_path = '~/.config/nvim/sessions'
# '''
