[[plugins]]
repo = 'Shougo/deol.nvim'
rev = '6a5adf9'
on_cmd = ['Deol']
hook_add = '''
    function FloatingDeol() abort
        let l:winwidth = float2nr(&columns * 0.9)
        let l:winheight = float2nr(&lines * 0.9)
        let l:wincol = float2nr((&columns - l:winwidth) / 2)
        let l:winrow = float2nr((&lines - l:winheight) / 2)
        execute 'Deol -split=floating'
            \ . ' -winwidth=' . l:winwidth
            \ . ' -winheight=' . l:winheight
            \ . ' -wincol=' . l:wincol
            \ . ' -winrow=' . l:winrow
    endfunction

    nnoremap <silent> <LEADER>df :call FloatingDeol()<CR>
    nnoremap <silent> <LEADER>dv :Deol -split=vertical <CR>
    nnoremap <silent> <LEADER>ds :Deol -split=horizontal <CR>
'''
hook_source = '''
    let g:deol#floating_border = 'single'
    tnoremap <C-q> <C-\><C-n>:q<CR>
'''
