[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
rev = '10b0da9' # 2023-06-15
on_event = 'BufRead'
hook_post_update = '''
TSUpdate
'''
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { 'python', 'javascript', 'typescript', 'tsx', 'toml' },
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
}
EOF
'''
