[[plugins]]
repo = 's1n7ax/nvim-window-picker'
rev = 'v2.0.3' # 2023-12-17
on_cmd = ['Neotree']
lua_source = '''
require('window-picker').setup({
    picker_config = {
        statusline_winbar_picker = {
            use_winber = 'always',
        },
    },
    show_propt = false,
})
'''
