[[plugins]]
repo = 't9md/vim-choosewin'
on_map = ['<Plug>(choosewin)']
hook_add = '''
    nmap - <Plug>(choosewin)
'''
hook_source = '''
    let g:choosewin_overlay_enable = 0

    let g:choosewin_blink_on_land = 0
    let g:choosewin_statusline_replace = 1
    let g:choosewin_tabline_replace = 1
'''
